/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionDeMovimientos.vista;

import gestionDeMovimientos.controlador.ControladorEditadoDeEmpleados;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author jesus
 */
public class JDialogEditadoEmpleado extends javax.swing.JDialog {

    private boolean flagNombreEmpleado = false;
    private boolean flagApellidoEmpleado = false;
     private ControladorEditadoDeEmpleados controladorEditadoDeEmpleados;
    public JDialogEditadoEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInsertarDatos = new javax.swing.JPanel();
        jLabelInsertarDatos = new javax.swing.JLabel();
        jLabelNumeroDeEmpleado = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonInsertarTexto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelInsertarDatos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelInsertarDatos.setText("Editar Empleados");

        jLabelNumeroDeEmpleado.setText("1");
        jLabelNumeroDeEmpleado.setToolTipText("Numero de empleado");

        jTextFieldNombre.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldNombre.setText("Nombre");
        jTextFieldNombre.setToolTipText("Nombre del Empleado");
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });

        jTextFieldApellido.setForeground(new java.awt.Color(126, 126, 126));
        jTextFieldApellido.setText("Apellidos");
        jTextFieldApellido.setToolTipText("Apellidos del Empleado");
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });

        jButtonInsertarTexto.setText("Editar");
        jButtonInsertarTexto.setToolTipText("Editar Empleado en BDD");
        jButtonInsertarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertarDatosLayout = new javax.swing.GroupLayout(jPanelInsertarDatos);
        jPanelInsertarDatos.setLayout(jPanelInsertarDatosLayout);
        jPanelInsertarDatosLayout.setHorizontalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelNumeroDeEmpleado)
                        .addGap(48, 48, 48)
                        .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarDatosLayout.createSequentialGroup()
                                .addComponent(jLabelInsertarDatos)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanelInsertarDatosLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonInsertarTexto)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanelInsertarDatosLayout.setVerticalGroup(
            jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarDatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInsertarDatos)
                .addGap(33, 33, 33)
                .addGroup(jPanelInsertarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumeroDeEmpleado))
                .addGap(18, 18, 18)
                .addComponent(jButtonInsertarTexto)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInsertarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        flagNombreEmpleado = controladorEditadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().isEmpty()) {
            flagNombreEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusGained
        flagApellidoEmpleado = controladorEditadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
    }//GEN-LAST:event_jTextFieldApellidoFocusGained

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        if (jTextFieldApellido.getText().isEmpty()) {
            flagApellidoEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

        }
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jButtonInsertarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarTextoActionPerformed
        flagApellidoEmpleado = controladorEditadoDeEmpleados.VaciarCampos(jTextFieldApellido, flagApellidoEmpleado);
        flagNombreEmpleado = controladorEditadoDeEmpleados.VaciarCampos(jTextFieldNombre, flagNombreEmpleado);

        boolean control = controladorEditadoDeEmpleados.EditarDatosEmpleados();
        if (control == false) {

            if (jTextFieldApellido.getText().isEmpty()) {
                flagApellidoEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);

            }
            if (jTextFieldNombre.getText().isEmpty()) {
                flagNombreEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

            }

        } else {
            flagApellidoEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Apellidos", jTextFieldApellido, flagApellidoEmpleado);
            flagNombreEmpleado = controladorEditadoDeEmpleados.RellenarCampos("Nombre", jTextFieldNombre, flagNombreEmpleado);

        }
    }//GEN-LAST:event_jButtonInsertarTextoActionPerformed

    public boolean isFlagNombreEmpleado() {
        return flagNombreEmpleado;
    }

    public void setFlagNombreEmpleado(boolean flagNombreEmpleado) {
        this.flagNombreEmpleado = flagNombreEmpleado;
    }

    public boolean isFlagApellidoEmpleado() {
        return flagApellidoEmpleado;
    }

    public void setFlagApellidoEmpleado(boolean flagApellidoEmpleado) {
        this.flagApellidoEmpleado = flagApellidoEmpleado;
    }

    public JLabel getjLabelNumeroDeEmpleado() {
        return jLabelNumeroDeEmpleado;
    }

    public void setjLabelNumeroDeEmpleado(JLabel jLabelNumeroDeEmpleado) {
        this.jLabelNumeroDeEmpleado = jLabelNumeroDeEmpleado;
    }

    public JPanel getjPanelInsertarDatos() {
        return jPanelInsertarDatos;
    }

    public void setjPanelInsertarDatos(JPanel jPanelInsertarDatos) {
        this.jPanelInsertarDatos = jPanelInsertarDatos;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public void setjTextFieldApellido(JTextField jTextFieldApellido) {
        this.jTextFieldApellido = jTextFieldApellido;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public void setjTextFieldNombre(JTextField jTextFieldNombre) {
        this.jTextFieldNombre = jTextFieldNombre;
    }
 
    public void setControladorEditadoDeEmpleados(ControladorEditadoDeEmpleados controladorEditadoDeEmpleados) {
        this.controladorEditadoDeEmpleados = controladorEditadoDeEmpleados;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEditadoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEditadoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEditadoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEditadoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogEditadoEmpleado dialog = new JDialogEditadoEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarTexto;
    private javax.swing.JLabel jLabelInsertarDatos;
    private javax.swing.JLabel jLabelNumeroDeEmpleado;
    private javax.swing.JPanel jPanelInsertarDatos;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

}
