/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionDeMovimientos.vista;
import gestionDeMovimientos.controlador.ControladorVisionadoDeEmpleados;
import javax.swing.JTable;
/**
 *
 * @author jesus
 */
public class JFrameVisionadoDeEmpleados extends javax.swing.JFrame {
      private final ControladorVisionadoDeEmpleados controladorVisionadoDeEmpleados;
    public JFrameVisionadoDeEmpleados() {
        initComponents();
        controladorVisionadoDeEmpleados = new ControladorVisionadoDeEmpleados(this);
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonRecargar = new javax.swing.JButton();
        jMenuBarVisionadoDeDatos = new javax.swing.JMenuBar();
        jMenuInsertadoDeDatos = new javax.swing.JMenu();
        jMenuItemInsertadoDeEmpleados = new javax.swing.JMenuItem();
        jMenuItemInsertadoDeMovimientosTexto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Numero De Empleado", "Nombre", "Apellido", "Cantidad De Movimientos", "Editar", "Borrar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(4).setResizable(false);
            jTableEmpleados.getColumnModel().getColumn(4).setPreferredWidth(25);
            jTableEmpleados.getColumnModel().getColumn(5).setPreferredWidth(25);
        }

        jButtonRecargar.setText("Recargar");
        jButtonRecargar.setToolTipText("Insertar los datos en el archivo Texto");
        jButtonRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jButtonRecargar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRecargar)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jMenuInsertadoDeDatos.setText("Insertar Datos");

        jMenuItemInsertadoDeEmpleados.setText("Insertar Empleados");
        jMenuItemInsertadoDeEmpleados.setToolTipText("Inserta todos los datos de movimientos y usuario");
        jMenuItemInsertadoDeEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertadoDeEmpleadosActionPerformed(evt);
            }
        });
        jMenuInsertadoDeDatos.add(jMenuItemInsertadoDeEmpleados);

        jMenuItemInsertadoDeMovimientosTexto.setText("Insertar Movimientos");
        jMenuItemInsertadoDeMovimientosTexto.setToolTipText("Inserta todos los datos de movimientos y usuario");
        jMenuItemInsertadoDeMovimientosTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertadoDeMovimientosTextoActionPerformed(evt);
            }
        });
        jMenuInsertadoDeDatos.add(jMenuItemInsertadoDeMovimientosTexto);

        jMenuBarVisionadoDeDatos.add(jMenuInsertadoDeDatos);

        setJMenuBar(jMenuBarVisionadoDeDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemInsertadoDeEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertadoDeEmpleadosActionPerformed
        controladorVisionadoDeEmpleados.AbrirInsertadoDeEmpleados();
    }//GEN-LAST:event_jMenuItemInsertadoDeEmpleadosActionPerformed

    private void jButtonRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecargarActionPerformed
     controladorVisionadoDeEmpleados.RellenarTabla(); 
    }//GEN-LAST:event_jButtonRecargarActionPerformed

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked
   
        controladorVisionadoDeEmpleados.SelectClic(evt, jTableEmpleados);
        
    }//GEN-LAST:event_jTableEmpleadosMouseClicked

    private void jMenuItemInsertadoDeMovimientosTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertadoDeMovimientosTextoActionPerformed
     
       controladorVisionadoDeEmpleados.AbrirInsertadoDeMovimientos();  
    }//GEN-LAST:event_jMenuItemInsertadoDeMovimientosTextoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       controladorVisionadoDeEmpleados.CerrarConexion();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       controladorVisionadoDeEmpleados.RellenarTabla();
    }//GEN-LAST:event_formWindowGainedFocus

    public JTable getjTableEmpleados() {
        return jTableEmpleados;
    }

    public void setjTableEmpleados(JTable jTableEmpleados) {
        this.jTableEmpleados = jTableEmpleados;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVisionadoDeEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    
                    JFrameVisionadoDeEmpleados visionadoDeDatosCreado= new JFrameVisionadoDeEmpleados();
                    visionadoDeDatosCreado.setLocationRelativeTo(null);
                    visionadoDeDatosCreado.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecargar;
    private javax.swing.JMenuBar jMenuBarVisionadoDeDatos;
    private javax.swing.JMenu jMenuInsertadoDeDatos;
    private javax.swing.JMenuItem jMenuItemInsertadoDeEmpleados;
    private javax.swing.JMenuItem jMenuItemInsertadoDeMovimientosTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmpleados;
    // End of variables declaration//GEN-END:variables
}
